import mongoose from "mongoose";
import dotenv from "dotenv";
import Book from "./model/book.model.js";

dotenv.config();

const sampleBooks = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 12.99,
    originalPrice: 15.99,
    category: "Fiction",
    subcategory: "Classic Literature",
    image: "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.",
    longDescription: "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel follows narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
    publishedYear: 1925,
    isbn: "978-0-7432-7356-5",
    pages: 180,
    language: "English",
    publisher: "Scribner",
    stock: 50,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 1250,
    tags: ["classic", "american literature", "jazz age", "wealth", "love"],
    dimensions: { height: 8.5, width: 5.5, depth: 0.8 },
    weight: 200,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 14.99,
    originalPrice: 18.99,
    category: "Fiction",
    subcategory: "Classic Literature",
    image: "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A gripping tale of racial injustice and childhood innocence in the American South.",
    longDescription: "To Kill a Mockingbird is a novel by Harper Lee published in 1960. It was immediately successful, winning the Pulitzer Prize, and has become a classic of modern American literature.",
    publishedYear: 1960,
    isbn: "978-0-06-112008-4",
    pages: 281,
    language: "English",
    publisher: "J.B. Lippincott & Co.",
    stock: 35,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 2100,
    tags: ["classic", "american literature", "racial justice", "coming of age"],
    dimensions: { height: 8.0, width: 5.2, depth: 0.9 },
    weight: 250,
    format: "Paperback",
    ageGroup: "Young Adult"
  },
  {
    title: "1984",
    author: "George Orwell",
    price: 13.99,
    originalPrice: 16.99,
    category: "Fiction",
    subcategory: "Dystopian",
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A dystopian social science fiction novel about totalitarian control and surveillance.",
    longDescription: "Nineteen Eighty-Four is a dystopian social science fiction novel and cautionary tale written by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime.",
    publishedYear: 1949,
    isbn: "978-0-452-28423-4",
    pages: 328,
    language: "English",
    publisher: "Secker & Warburg",
    stock: 40,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 1800,
    tags: ["dystopian", "science fiction", "totalitarianism", "surveillance"],
    dimensions: { height: 7.8, width: 5.1, depth: 1.0 },
    weight: 280,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 11.99,
    originalPrice: 14.99,
    category: "Fiction",
    subcategory: "Romance",
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A romantic novel of manners written by Jane Austen, following the character development of Elizabeth Bennet.",
    longDescription: "Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.",
    publishedYear: 1813,
    isbn: "978-0-14-143951-8",
    pages: 432,
    language: "English",
    publisher: "T. Egerton, Whitehall",
    stock: 25,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 1650,
    tags: ["romance", "classic literature", "manners", "social commentary"],
    dimensions: { height: 7.5, width: 5.0, depth: 1.2 },
    weight: 320,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 15.99,
    originalPrice: 19.99,
    category: "Fiction",
    subcategory: "Coming of Age",
    image: "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A coming-of-age story about teenage rebellion and alienation in 1950s America.",
    longDescription: "The Catcher in the Rye is a novel by J. D. Salinger, partially published in serial form in 1945-1946 and as a novel in 1951. It was originally intended for adults but is often read by adolescents for its themes of teenage angst and alienation.",
    publishedYear: 1951,
    isbn: "978-0-316-76948-0",
    pages: 234,
    language: "English",
    publisher: "Little, Brown and Company",
    stock: 30,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.3,
    reviewCount: 1400,
    tags: ["coming of age", "teenage rebellion", "alienation", "american literature"],
    dimensions: { height: 8.2, width: 5.4, depth: 0.7 },
    weight: 220,
    format: "Paperback",
    ageGroup: "Young Adult"
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 16.99,
    originalPrice: 21.99,
    category: "Fiction",
    subcategory: "Fantasy",
    image: "https://m.media-amazon.com/images/I/712cDO7d73L._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/712cDO7d73L._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/712cDO7d73L._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A fantasy novel about a hobbit's unexpected journey to help dwarves reclaim their homeland.",
    longDescription: "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune for best juvenile fiction.",
    publishedYear: 1937,
    isbn: "978-0-547-92822-7",
    pages: 310,
    language: "English",
    publisher: "George Allen & Unwin",
    stock: 45,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 2800,
    tags: ["fantasy", "adventure", "middle-earth", "hobbit", "dwarves"],
    dimensions: { height: 8.0, width: 5.3, depth: 1.1 },
    weight: 300,
    format: "Paperback",
    ageGroup: "All Ages"
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    price: 19.99,
    originalPrice: 24.99,
    category: "Self-Help",
    subcategory: "Personal Development",
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "An easy and proven way to build good habits and break bad ones.",
    longDescription: "Atomic Habits is a comprehensive guide on how to change your habits and get 1% better every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    publishedYear: 2018,
    isbn: "978-0-7352-1129-2",
    pages: 320,
    language: "English",
    publisher: "Avery",
    stock: 60,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 3200,
    tags: ["self-help", "habits", "productivity", "personal development", "psychology"],
    dimensions: { height: 9.0, width: 6.0, depth: 1.0 },
    weight: 350,
    format: "Hardcover",
    ageGroup: "Adult"
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 18.99,
    originalPrice: 22.99,
    category: "Non-Fiction",
    subcategory: "History",
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A brief history of humankind, exploring how Homo sapiens came to dominate the world.",
    longDescription: "Sapiens: A Brief History of Humankind is a book by Yuval Noah Harari, first published in Hebrew in Israel in 2011 and in English in 2014. The book surveys the history of humankind from the evolution of archaic human species in the Stone Age up to the twenty-first century.",
    publishedYear: 2014,
    isbn: "978-0-06-231609-7",
    pages: 443,
    language: "English",
    publisher: "Harper",
    stock: 40,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 2500,
    tags: ["history", "anthropology", "evolution", "civilization", "philosophy"],
    dimensions: { height: 8.3, width: 5.5, depth: 1.3 },
    weight: 380,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 17.99,
    originalPrice: 20.99,
    category: "Non-Fiction",
    subcategory: "Finance",
    image: "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Timeless lessons on wealth, greed, and happiness through the lens of psychology.",
    longDescription: "The Psychology of Money explores the strange ways people think about money and teaches you how to make better sense of one of life's most important topics. Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life's most important topics.",
    publishedYear: 2020,
    isbn: "978-0-85204-844-8",
    pages: 256,
    language: "English",
    publisher: "Harriman House",
    stock: 35,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 1900,
    tags: ["finance", "psychology", "wealth", "money", "investing"],
    dimensions: { height: 8.5, width: 5.5, depth: 0.8 },
    weight: 280,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Educated",
    author: "Tara Westover",
    price: 16.99,
    originalPrice: 19.99,
    category: "Non-Fiction",
    subcategory: "Memoir",
    image: "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A memoir about a woman who grows up in a survivalist Mormon family and eventually goes on to earn a PhD from Cambridge University.",
    longDescription: "Educated is a memoir by Tara Westover published in 2018. It describes her struggle to reconcile her desire for education and autonomy with her family's rigid ideology and isolation. Westover was seventeen the first time she set foot in a classroom.",
    publishedYear: 2018,
    isbn: "978-0-399-59050-4",
    pages: 334,
    language: "English",
    publisher: "Random House",
    stock: 30,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 2200,
    tags: ["memoir", "education", "family", "resilience", "self-discovery"],
    dimensions: { height: 8.0, width: 5.2, depth: 1.0 },
    weight: 300,
    format: "Paperback",
    ageGroup: "Adult"
  },
  // Self-Help Books
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    price: 18.99,
    originalPrice: 22.99,
    category: "Self-Help",
    subcategory: "Personal Development",
    image: "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A powerful lesson in personal change and leadership principles.",
    longDescription: "The 7 Habits of Highly Effective People is a business and self-help book written by Stephen Covey. Covey presents an approach to being effective in attaining goals by aligning oneself to what he calls 'true north' principles of a character ethic that he presents as universal and timeless.",
    publishedYear: 1989,
    isbn: "978-0-7432-6951-3",
    pages: 432,
    language: "English",
    publisher: "Free Press",
    stock: 25,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 3500,
    tags: ["self-help", "leadership", "personal development", "productivity"],
    dimensions: { height: 9.0, width: 6.0, depth: 1.2 },
    weight: 400,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 14.99,
    originalPrice: 17.99,
    category: "Self-Help",
    subcategory: "Success",
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "The classic guide to achieving wealth and success through positive thinking.",
    longDescription: "Think and Grow Rich is a 1937 motivational personal development and self-help book written by Napoleon Hill and inspired by a suggestion from Scottish-American businessman Andrew Carnegie.",
    publishedYear: 1937,
    isbn: "978-1-58006-930-4",
    pages: 320,
    language: "English",
    publisher: "Ralston Society",
    stock: 30,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 2800,
    tags: ["self-help", "success", "wealth", "motivation"],
    dimensions: { height: 8.5, width: 5.5, depth: 0.9 },
    weight: 350,
    format: "Paperback",
    ageGroup: "Adult"
  },
  // Philosophy Books
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    price: 13.99,
    originalPrice: 16.99,
    category: "Philosophy",
    subcategory: "Stoicism",
    image: "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Personal reflections on Stoic philosophy by the Roman Emperor.",
    longDescription: "Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy.",
    publishedYear: 180,
    isbn: "978-0-14-044933-4",
    pages: 256,
    language: "English",
    publisher: "Penguin Classics",
    stock: 20,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 1200,
    tags: ["philosophy", "stoicism", "ancient wisdom", "meditation"],
    dimensions: { height: 7.8, width: 5.1, depth: 0.8 },
    weight: 280,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "The Republic",
    author: "Plato",
    price: 15.99,
    originalPrice: 19.99,
    category: "Philosophy",
    subcategory: "Political Philosophy",
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Plato's foundational work on justice, the ideal state, and the nature of reality.",
    longDescription: "The Republic is a Socratic dialogue, written by Plato around 380 BCE, concerning justice, the order and character of the just city-state, and the just man.",
    publishedYear: -380,
    isbn: "978-0-14-044914-3",
    pages: 416,
    language: "English",
    publisher: "Penguin Classics",
    stock: 15,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 800,
    tags: ["philosophy", "political theory", "justice", "ancient greece"],
    dimensions: { height: 8.0, width: 5.2, depth: 1.0 },
    weight: 320,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Thus Spoke Zarathustra",
    author: "Friedrich Nietzsche",
    price: 16.99,
    originalPrice: 20.99,
    category: "Philosophy",
    subcategory: "Existentialism",
    image: "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81gep1Sq3zL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Nietzsche's philosophical novel about the death of God and the Übermensch.",
    longDescription: "Thus Spoke Zarathustra is a philosophical novel by Friedrich Nietzsche, composed in four parts between 1883 and 1885. Much of the work deals with ideas such as the 'eternal recurrence of the same', the parable on the 'death of God', and the 'prophecy' of the Übermensch.",
    publishedYear: 1883,
    isbn: "978-0-14-044118-5",
    pages: 352,
    language: "English",
    publisher: "Penguin Classics",
    stock: 18,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: false,
    rating: 4.2,
    reviewCount: 600,
    tags: ["philosophy", "nietzsche", "existentialism", "german philosophy"],
    dimensions: { height: 7.9, width: 5.1, depth: 0.9 },
    weight: 300,
    format: "Paperback",
    ageGroup: "Adult"
  },
  // Computer Science Books
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 39.99,
    originalPrice: 49.99,
    category: "Computer Science",
    subcategory: "Programming",
    image: "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81QuEGw8veL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "A Handbook of Agile Software Craftsmanship for professional developers.",
    longDescription: "Clean Code is a software engineering book written by Robert C. Martin. The book illustrates how to write clean code and shows the reader how to transform bad code into clean code.",
    publishedYear: 2008,
    isbn: "978-0-13-235088-4",
    pages: 464,
    language: "English",
    publisher: "Prentice Hall",
    stock: 40,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 4200,
    tags: ["programming", "software engineering", "clean code", "best practices"],
    dimensions: { height: 9.2, width: 7.0, depth: 1.1 },
    weight: 450,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    price: 89.99,
    originalPrice: 99.99,
    category: "Computer Science",
    subcategory: "Algorithms",
    image: "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "The comprehensive guide to algorithms and data structures.",
    longDescription: "Introduction to Algorithms is a book on computer programming by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein. The book has been widely used as the textbook for algorithms courses at many universities.",
    publishedYear: 2009,
    isbn: "978-0-262-03384-8",
    pages: 1312,
    language: "English",
    publisher: "MIT Press",
    stock: 25,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 1800,
    tags: ["algorithms", "computer science", "data structures", "programming"],
    dimensions: { height: 10.0, width: 7.5, depth: 1.8 },
    weight: 800,
    format: "Hardcover",
    ageGroup: "Adult"
  },
  {
    title: "The Pragmatic Programmer",
    author: "David Thomas",
    price: 34.99,
    originalPrice: 39.99,
    category: "Computer Science",
    subcategory: "Software Development",
    image: "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/91HPG31dTwL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Your journey to mastery in software development.",
    longDescription: "The Pragmatic Programmer: Your Journey to Mastery is a book about computer programming and software engineering, written by David Thomas and Andrew Hunt and published in 1999.",
    publishedYear: 1999,
    isbn: "978-0-201-61622-4",
    pages: 352,
    language: "English",
    publisher: "Addison-Wesley",
    stock: 35,
    isAvailable: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 3200,
    tags: ["programming", "software development", "pragmatic", "best practices"],
    dimensions: { height: 9.0, width: 6.0, depth: 1.0 },
    weight: 380,
    format: "Paperback",
    ageGroup: "Adult"
  },
  {
    title: "Design Patterns",
    author: "Gang of Four",
    price: 44.99,
    originalPrice: 54.99,
    category: "Computer Science",
    subcategory: "Software Design",
    image: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
    images: [
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UF894,1000_QL80_.jpg"
    ],
    description: "Elements of Reusable Object-Oriented Software design patterns.",
    longDescription: "Design Patterns: Elements of Reusable Object-Oriented Software is a software engineering book describing software design patterns.",
    publishedYear: 1994,
    isbn: "978-0-201-63361-0",
    pages: 395,
    language: "English",
    publisher: "Addison-Wesley",
    stock: 20,
    isAvailable: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 2500,
    tags: ["design patterns", "object-oriented", "software design", "programming"],
    dimensions: { height: 9.1, width: 6.1, depth: 1.2 },
    weight: 420,
    format: "Paperback",
    ageGroup: "Adult"
  }
];

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MongoDBURI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("Connected to MongoDB");

    // Clear existing books
    await Book.deleteMany({});
    console.log("Cleared existing books");

    // Insert sample books
    await Book.insertMany(sampleBooks);
    console.log("Sample books inserted successfully");

    // Close connection
    await mongoose.connection.close();
    console.log("Database connection closed");
  } catch (error) {
    console.error("Error seeding database:", error);
  }
};

seedDatabase();
